version: '3'

services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - challengenet
    ports:
      - 8080:80
    depends_on:
      - app

  app:
    build: 
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./node:/usr/src/app
    networks:
      - challengenet
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    container_name: db
    tty: true
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - challengenet

networks:
  challengenet:
    driver: bridge